runtime:
  nodePool: large_nodes

language: c

compiler: gcc

env:
    global:
        - SANITYCHECK_OPTIONS=" -p native_posix -T tests/kernel --inline-logs -N --retry-failed 3 -v "
        - MATRIX_BUILDS="5"
        - ZEPHYR_TOOLCHAIN_VARIANT="zephyr"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.11.2
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"

build:
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.11.6
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - git submodule update --remote
      - west init -l zephyr
      - west update
      - cd zephyr
      - export QEMU_BIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/
      - export QEMU_BIOS=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/share/qemu
      - export DTC=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
      - source zephyr-env.sh
      - TESTCOMMIT=`git describe`;
      - mkdir -p ../output/${TESTCOMMIT}
      - git describe > ../output/${TESTCOMMIT}/commit.txt
      - >
        ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${SANITYCHECK_OPTIONS};
    on_success:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./sanity-out/sanitycheck.xml ]; then
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
          TESTCOMMIT=`git describe`;
          cat ./sanity-out/sanitycheck.xml;
          cp ./sanity-out/sanitycheck.xml  ../output/${TESTCOMMIT}/results-${TESTCOMMIT}-${MATRIX_BUILD}.xml;
          export S3_PATH="s3://builds.zephyrproject.org/daily_tests/";
          aws s3 sync ../output/ ${S3_PATH}
        fi;
    on_failure:
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./sanity-out/sanitycheck.xml ]; then
          cp ./sanity-out/sanitycheck.xml ../shippable/testresults/;
          TESTCOMMIT=`git describe`;
          cat ./sanity-out/sanitycheck.xml;
          cp ./sanity-out/sanitycheck.xml  ../output/${TESTCOMMIT}/results-${TESTCOMMIT}-${MATRIX_BUILD}.xml;
          export S3_PATH="s3://builds.zephyrproject.org/daily_tests/";
          aws s3 sync ../output/ ${S3_PATH}
        fi;

integrations:
  generic:
    - integrationName: aws_s3
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds+int+399+7809482394022958124@lists.zephyrproject.org
      branches:
        only:
          - master
      on_success: always
      on_failure: always
