# Copyright (c) 2020 Intel Corp.
# SPDX-License-Identifier: Apache-2.0

name: Publish commit for daily testing

on: push

jobs:
  get_version:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: install-pip
      run: |
        pip3 install gitpython

    - name: checkout
      uses: actions/checkout@v2

    - name: Upload to AWS S3
      env:
        RELEASE: ${{ steps.tag.outputs.RELEASE }}
      run: |
        aws s3 cp s3://testing.zephyrproject.org/internal/versions.json .
        scripts/version_mgr.py
        aws s3 cp versions.json s3://testing.zephyrproject.org/internal/versions.json
