# Copyright (c) 2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Process Test Results

# Either a daily based on schedule/cron or only on tag push
on:
  schedule:
    - cron:  '50 22 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: checkout
      uses: actions/checkout@v2

      #    - name: install-pkgs
      #run: |
      #  sudo apt-get install -y ninja-build doxygen

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-test-pip

    - name: install-pip
      run: |
        pip3 install setuptools
        pip3 install junit2html

    - name: Upload Results
      uses: actions/upload-artifact@master
      continue-on-error: True
      with:
        name: results
        path: output/results.xml

    - name: Download Versions
      run: |
        aws s3 cp s3://testing.zephyrproject.org/daily_tests/versions.json .
        latest=`cat versions.json |jq -r  '.[-1] '`
        echo "Latest is ${latest}";
        mkdir ${latest} output
        aws s3 sync  s3://testing.zephyrproject.org/daily_tests/${latest}  ${latest}
        python3 ./scripts/merge_junit.py  ${latest}/*.xml > output/results.xml
